// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Notify.proto

package org.ogcs.protobuf;

public final class NotifyProto {
  private NotifyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NotifyMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NotifyMessage)
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<NotifyMessage> {

    /**
     * <code>optional int32 notifyId = 1;</code>
     */
    boolean hasNotifyId();
    /**
     * <code>optional int32 notifyId = 1;</code>
     */
    int getNotifyId();
  }
  /**
   * Protobuf type {@code NotifyMessage}
   */
  public static final class NotifyMessage extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        NotifyMessage> implements
      // @@protoc_insertion_point(message_implements:NotifyMessage)
      NotifyMessageOrBuilder {
    // Use NotifyMessage.newBuilder() to construct.
    private NotifyMessage(ExtendableBuilder<NotifyMessage, ?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NotifyMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NotifyMessage defaultInstance;
    public static NotifyMessage getDefaultInstance() {
      return defaultInstance;
    }

    public NotifyMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NotifyMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              notifyId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NotifyProto.internal_static_NotifyMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NotifyProto.internal_static_NotifyMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NotifyMessage.class, Builder.class);
    }

    public static com.google.protobuf.Parser<NotifyMessage> PARSER =
        new com.google.protobuf.AbstractParser<NotifyMessage>() {
      public NotifyMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NotifyMessage(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<NotifyMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int NOTIFYID_FIELD_NUMBER = 1;
    private int notifyId_;
    /**
     * <code>optional int32 notifyId = 1;</code>
     */
    public boolean hasNotifyId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 notifyId = 1;</code>
     */
    public int getNotifyId() {
      return notifyId_;
    }

    private void initFields() {
      notifyId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      ExtensionWriter extensionWriter =
          newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, notifyId_);
      }
      extensionWriter.writeUntil(1001, output);
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, notifyId_);
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static NotifyMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NotifyMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NotifyMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NotifyMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NotifyMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static NotifyMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static NotifyMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static NotifyMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static NotifyMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static NotifyMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(NotifyMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NotifyMessage}
     */
    public static final class Builder extends
        ExtendableBuilder<
          NotifyMessage, Builder> implements
        // @@protoc_insertion_point(builder_implements:NotifyMessage)
        NotifyMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return NotifyProto.internal_static_NotifyMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return NotifyProto.internal_static_NotifyMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                NotifyMessage.class, Builder.class);
      }

      // Construct using dev.tinyz.core.rpc.NotifyProto.NotifyMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        notifyId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return NotifyProto.internal_static_NotifyMessage_descriptor;
      }

      public NotifyMessage getDefaultInstanceForType() {
        return NotifyMessage.getDefaultInstance();
      }

      public NotifyMessage build() {
        NotifyMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public NotifyMessage buildPartial() {
        NotifyMessage result = new NotifyMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.notifyId_ = notifyId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof NotifyMessage) {
          return mergeFrom((NotifyMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(NotifyMessage other) {
        if (other == NotifyMessage.getDefaultInstance()) return this;
        if (other.hasNotifyId()) {
          setNotifyId(other.getNotifyId());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!extensionsAreInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        NotifyMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (NotifyMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int notifyId_ ;
      /**
       * <code>optional int32 notifyId = 1;</code>
       */
      public boolean hasNotifyId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 notifyId = 1;</code>
       */
      public int getNotifyId() {
        return notifyId_;
      }
      /**
       * <code>optional int32 notifyId = 1;</code>
       */
      public Builder setNotifyId(int value) {
        bitField0_ |= 0x00000001;
        notifyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 notifyId = 1;</code>
       */
      public Builder clearNotifyId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        notifyId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:NotifyMessage)
    }

    static {
      defaultInstance = new NotifyMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:NotifyMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NotifyMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NotifyMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014Notify.proto\"(\n\rNotifyMessage\022\020\n\010notif" +
      "yId\030\001 \001(\005*\005\010d\020\351\007B&\n\022dev.tinyz.core.rpcB\013" +
      "NotifyProtoH\001\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_NotifyMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NotifyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_NotifyMessage_descriptor,
        new String[] { "NotifyId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
